### PR TITLE
I, Mohammed Aadil has completed assignment 1 of Production Module

### PR DESCRIPTION
**Pull request by aadil-shaikh786**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding features like lag, returns, and moving averages to analyze stock data from parquet files.

## What did you learn from the changes you have made?
Learned to efficiently handle and process large datasets using Dask and compute rolling averages in pandas.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Yes, keeping all computations in Dask to optimize performance for large-scale data.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Faced directory path and file handling issues. Overcame them by debugging and using the correct Dask and glob configurations.

## How were these changes tested?
Tested by inspecting data outputs at each step using .head() and verifying correctness of computed features.

## A reference to a related issue in your repository (if applicable)
N/A

## Checklist
- [ Yes ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by aadil-shaikh786** [comment]
Completed Assignment 2 and Assignment 3

**Comment by KasraVakiloroayaei** [comment]
A1: Complete

Please note that each assignment should be under a separate branch. This can make it very difficult for the learning support to find your code and make the necessary comments.

**Comment by KasraVakiloroayaei** [comment]
A2: Complete

**Comment by KasraVakiloroayaei** [comment]
A3: complete 

Please note that you cannot have a negative R² values for Models C and D. Inherently the R² is from the quadratic function, in which it does not have any negative y values (response) across the entire domain from negative infinity to positive infinity.

**Pull request merged**
